[project]
name = "dspy-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dspy>=2.6.27",
    "fastmcp>=2.9.1",
    "func-timeout>=4.3.5",
    "llama-stack-client>=0.2.17",
    "mcp>=1.10.1",
    "mlflow>=3.3.2",
    "pandas>=2.3.0",
    "pydantic>=2.11.7",
]
